### ISSUE TITLE
`load_team_season_stats` and `load_player_season_stats` return the same output

### ISSUE THREAD

**Issue by nanodino** [nwslR/nwslpy#4]
When called, the two function return the same values. It is not only the column names that are equal, but all of the data that is identical. This can be proven by using the `assert_frame_equal` method in pandas:

```
import nwslpy
import pandas as pd
import datetime as dt

last_season = str(dt.date.today().year - 1)
this_season = str(dt.date.today().year)

all_teams = nwslpy.load_teams()
active_teams = (all_teams[all_teams["last_season"].astype(str)==this_season]).reset_index()

idx = {name: i for i, name in enumerate(list(active_teams), start = 0)}
each_team_stats = {}
each_team_player_stats = {}


for team in active_teams.itertuples(index=False):
    abbreviation = team[idx["team_abbreviation"]]
    each_team_stats[abbreviation] = nwslpy.load_team_season_stats(abbreviation, this_season).reset_index()
    each_team_player_stats[abbreviation] = nwslpy.load_player_season_stats(abbreviation, this_season).reset_index()

    print(f'Differences between frames for {abbreviation}: {pd.testing.assert_frame_equal(each_team_stats[abbreviation], each_team_player_stats[abbreviation])}')

```

Running this will output a string of the shape `Differences between frames for CHI: None` for each team.

**Comment by agale123** [comment]
It looks like there is an issue with the 2023 data from nwslR which this is querying. The tables appear to be correct for 2022 @adror1 are you aware of the 2023 player season stats table not being broken down by player?

**Comment by adror1** [comment]
Yikes! On it right now...

**Comment by adror1** [comment]
Should be fixed, was an issue w/ the way the upload worked. Going to try to fix it this weekend, but the data is right now.

**Comment by agale123** [comment]
Yup, it looks fixed now. Thanks Arielle!
